# https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/alacritty/alacritty.yml
#
# use tmux as shell
# shell:
#     program: /usr/local/bin/tmux
#     args:
#      - -u # force UTF-8 in tmux

key_bindings:
    # for alacritty
    - { key: N,       mods: Super,  action: SpawnNewInstance }
    - { key: Minus,   mods: Super,  action: DecreaseFontSize }
    - { key: Equals,  mods: Super,  action: IncreaseFontSize }
    - { key: Key0,    mods: Super,  action: ResetFontSize }
    # prevent cmd w from clasing window
    - { key: W,       mods: Super,  action: ResetFontSize }
    - {
          key: Comma,
          mods: Command,
          command:
              { program: "open", args: ["~/.config/alacritty/alacritty.yml"] },
      }

    # Some keys to match iterm / osx, unsure whether to use or not...
    # - { key: D,       mods: Super,        chars: "\x01\x25" }
    # - { key: D,       mods: Super|Shift,  chars: "\x01\x22" }
    # - { key: W,       mods: Super,        chars: "\x01\x78" }
    # - { key: H,       mods: Super|Alt,    chars: "\x01\x68" }
    # - { key: L,       mods: Super|Alt,    chars: "\x01\x6c" }
    # - { key: K,       mods: Super|Alt,    chars: "\x01\x6b" }
    # - { key: J,       mods: Super|Alt,    chars: "\x01\x6a" }
    # - { key: T,       mods: Super,        chars: "\x01\x63" }
    # - { key: Return,  mods: Super|Shift,  chars: "\x01\x7a" }
    # - { key: Right,   mods: Super,        chars: "\x05" }
    # - { key: Left,    mods: Super,        chars: "\x05" }
    # - { key: Right,   mods: Alt,          chars: "\xc6\x92" }
    # - { key: Left,    mods: Alt,          chars: "\x05" }

    # Need to map alt <num> to esc <num> for tmux layouts but wont ta keep
    # 2 and 4 for x and x so remapping to ctrl
    - { key: Key1,      mods: Control,       chars: "\x1b1"                       }
    - { key: Key2,      mods: Control,       chars: "\x1b2"                       }
    - { key: Key3,      mods: Control,       chars: "\x1b3"                       }
    - { key: Key4,      mods: Control,       chars: "\x1b4"                       }
    - { key: Key5,      mods: Control,       chars: "\x1b5"                       }

env:
    # TERM env customization.
    #
    # If this property is not set, alacritty will set it to xterm-256color.
    #
    # Note that some xterm terminfo databases don't declare support for italics.
    # You can verify this by checking for the presence of `smso` and `sitm` in
    # `infocmp xterm-256color`.
    TERM: xterm-256color

live_config_reload: true

window:
    padding:
        x: 2
        y: 2

scrolling:
    # Maximum number of lines in the scrollback buffer.
    # Specifying '0' will disable scrolling.
    history: 10000

    # Number of lines the viewport will move for every line scrolled when
    # scrollback is enabled (history > 0).
    multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

background_opacity: 1.0

font:
    # Point size
    size: 13.0
    normal:
        family: SauceCodePro Nerd Font
        style: Regular
    bold:
        family: SauceCodePro Nerd Font
        style: Bold
    italic:
        family: SauceCodePro Nerd Font
        style: Italic
    bold_italic:
        family: SauceCodePro Nerd Font
        style: Bold Italic

# Colors (Nord)
colors:
    # Default colors
    primary:
        background: "#2E3440"
        foreground: "#D8DEE9"

    # Normal colors
    normal:
        black: "#3B4252"
        red: "#BF616A"
        green: "#A3BE8C"
        yellow: "#EBCB8B"
        blue: "#81A1C1"
        magenta: "#B48EAD"
        cyan: "#88C0D0"
        white: "#E5E9F0"

    # Bright colors
    bright:
        black: "#4C566A"
        red: "#BF616A"
        green: "#A3BE8C"
        yellow: "#EBCB8B"
        blue: "#81A1C1"
        magenta: "#B48EAD"
        cyan: "#8FBCBB"
        white: "#ECEFF4"
