key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Key0, mods: Command, action: ResetFontSize }

env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: alacritty

live_config_reload: true

window:
  padding:
    x: 2
    y: 2

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

background_opacity: 1.0

font:
  # Point size
  size: 13.0
  normal:
    family: SauceCodePro Nerd Font
    style: Regular
  bold:
    family: SauceCodePro Nerd Font
    style: Bold
  italic:
    family: SauceCodePro Nerd Font
    style: Italic
  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

# Colors (Nord)
colors:
   # Default colors
   primary:
     background: '#2E3440'
     foreground: '#D8DEE9'

   # Normal colors
   normal:
     black:   '#3B4252'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#88C0D0'
     white:   '#E5E9F0'

   # Bright colors
   bright:
     black:   '#4C566A'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#8FBCBB'
     white:   '#ECEFF4'
